Free unused memory in Data.from
spacebudz/lucid pull request #232
Opened 2023-11-01 16:04 UTC by yHSJ

At JPG Store, we have been dealing with memory leaks in our code that uses either Lucid or the CML. After some research, we discovered that the CML does a lot of `clone`s to avoid issues with freed memory across the WASM boundary ( https://github.com/dcSpark/cardano-multiplatform-lib/issues/142#issuecomment-1281810732). 

Any object that is returned from WASM to JavaScript seems to never get garbage collected. Thus, **all** objects returned from wasm to the js runtime must be freed, including intermediary values when chaining function calls together.

This PR specifically only fixes  the memory usage in the `Data.from` function to resolve the following issue: https://github.com/spacebudz/lucid/issues/222

I will continue to fix the memory management over time, as I have free time. However, I would argue it is best to merge these smaller pieces whenever they are done, as they will reduce the memory footprint of several applications relying on Lucid.

2023-11-01 20:10 UTC, joacohoyos requested changes
Small comment. We might also want to add a comment to the freeable class cause other people might not have the context we have due to our internal discussions

2023-11-01 20:10 UTC, joacohoyos commented on src/utils/freeable.ts
> +export type FreeableBucket = Array<Freeable | undefined>;
Make this so it's also nullable. I've seen cases on jpg where I had to add null also

2023-11-01 20:10 UTC, joacohoyos commented on src/utils/freeable.ts
> +  static free(...bucket: (Freeable | undefined)[]) {
same here add null

2023-11-04 22:10 UTC, yHSJ commented
Closing in favor of https://github.com/spacebudz/lucid/pull/234 which includes managing WASM memory everywhere it's used.

2023-11-04 22:10 UTC, closed without merging